---
- name: Validate developer_hub role action
  ansible.builtin.assert:
    that:
      - (component_action | default(rhcl_action)) in ["install", "remove", "validate"]
    fail_msg: "Requested developer_hub action must be install, remove, or validate."

- name: Run developer_hub action
  ansible.builtin.include_tasks: "{{ component_action | default(rhcl_action) }}.yml"
