package com.redhat.rhoai.assistant.domain;

public enum ModelChangeReason {
    MANUAL_SELECTION,
    MODEL_UNAVAILABLE,
    CAPACITY_EXHAUSTED,
    REQUEST_TIMEOUT,
    CONTEXT_LIMIT_EXCEEDED,
    UNSUPPORTED_CAPABILITY,
    PROVIDER_ERROR,
    LOWER_COST_SELECTION,
    LOWER_LATENCY_SELECTION,
    DEFAULT_PRIORITY
}
