---
- name: Validate coredns_dns role action
  ansible.builtin.assert:
    that:
      - (component_action | default(rhcl_action)) in ["install", "remove", "validate"]
    fail_msg: "Requested coredns_dns action must be install, remove, or validate."

- name: Run coredns_dns action
  ansible.builtin.include_tasks: "{{ component_action | default(rhcl_action) }}.yml"
