apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: red-bank-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: quay.io/hodrigohamalho/red-bank-backend
    newName: quay.io/hodrigohamalho/red-bank-backend
    newTag: prod
  - name: quay.io/hodrigohamalho/red-bank-frontend
    newName: quay.io/hodrigohamalho/red-bank-frontend
    newTag: prod
