---
- name: Remove the CoreDNS DNS provider configuration
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: coredns_dns
      vars:
        rhcl_action: remove
