---
- name: Install Gateway API prerequisites
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: gateway_api
      vars:
        rhcl_action: install
