---
- name: Validate Gateway API prerequisites
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: gateway_api
      vars:
        component_action: validate
