---
- name: Remove Grafana Operator + RHCL dashboards
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: grafana
      vars:
        rhcl_action: remove
