---
- name: Remove Let's Encrypt ClusterIssuers
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: letsencrypt
      vars:
        rhcl_action: remove
