---
- name: Install MCP gateway
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  environment: "{{ {'KUBECONFIG': lookup('ansible.builtin.env', 'KUBECONFIG')} if lookup('ansible.builtin.env', 'KUBECONFIG') | length > 0 else {} }}"
  roles:
    - role: mcp_gateway
      vars:
        rhcl_action: install
