---
- name: Enable OpenShift User Workload Monitoring
  hosts: rhcl_clusters
  gather_facts: false
  collections:
    - kubernetes.core
  roles:
    - role: monitoring
      vars:
        rhcl_action: install
